Use cadical from homebrew-core
Cadical was added to homebrew-core in May 2021 [1].  If Cadical is
already installed from homebrew-core, then installing Yices from this
tap fails with

  > Error: cadical 1.7.0 is already installed
  > To install 1.2.2, first run:
  >   brew unlink cadical

Homebrew-core's version is newer, so the simplest fix is to just use
that one.

[1]: https://github.com/Homebrew/homebrew-core/blob/a3267a34c4be8286044ab9aad1d98e685bbd63ab/Formula/cadical.rb